### ISSUE TITLE
Debian 10 - Qt::endl > endl and position() > pos()

### ISSUE THREAD

**Issue by HaakonME** [eticre/povmodeler#3]
Hi, thank you for updating Kpovmodeler to Povmodeler, keep up the good work. :-) 

On Debian 10, I ran into two issues before I was able to compile Povmodeler, which did not occure with the older Kpovmodeler in your other repo.

1) Qt::endl had to be replaced by endl.
2) e->position() had to be replaced by e->pos().

**Comment by eticre** [comment]
Hello
archlinux Is updated to Qt 5.15
Qt::endl; Is required instead endl; 

⁣Ottieni TypeApp per Android ​

Il giorno 14 mag 2021, 13:39, alle ore 13:39, Haakon Meland Eriksen ***@***.***> ha scritto:

**Comment by HaakonME** [comment]
Right, I believe Debian 10 is at 5.11.x. Closing.
